name: CI process
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Build project
        run: ./gradlew build

      - name: Sonar analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew test jacocoTestReport sonarqube

      - name: Show dirs
        run: |
          ls -all
          cd build
          ls -all
          cd libs
          ls -all
#
#      - name: Build
#        id: build
#        uses: cloudposse/github-action-docker-build-push@main
#        with:
#          registry: registry.hub.docker.com
#          organization: denny0304
#          repository: learn-ci
#          login: "${{ secrets.DOCKERHUB_USERNAME }}"
#          password: "${{ secrets.DOCKERHUB_TOKEN }}"
#          platforms: linux/amd64,linux/arm64

  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build project
        run: ./gradlew build

      - name: Show dirs
        run: |
          ls -all
          cd build
          ls -all
          cd libs
          ls -all

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: user/app:latest


